server:
  port: 8081

# datasource
spring:
  config:
    import: env.yml

#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#      pool:
#        max-idle: ${REDIS_POOL_MAX_IDLE}
#        min-idle: ${REDIS_POOL_MIN_IDLE}
#        max-active: ${REDIS_POOL_MAX_ACTIVE}
#        max-wait: ${REDIS_POOL_MAX_WAIT}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
  # jpa
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update

FEIGN_URL: localhost:8080

cloud:
  aws:
    s3:
      bucket: moa-timecapsule-images
    credentials:
      access-key: AKIAS2FT2X24HM2ZQ2MA
      secret-key: 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
    region:
      static: ap-southeast-2
      auto: false
    stack:
      auto: false
