name: Deploy to Amazon ECS

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

env:
  AWS_REGION: ap-southeast-2                  # set this to your preferred AWS region, e.g. us-west-1
  ECR_REGISTRY: 193650671288.dkr.ecr.ap-southeast-2.amazonaws.com
  ECR_REPOSITORY: moa-timecapsule             # set this to your Amazon ECR repository name
  IMAGE_TAG: latest                

jobs:
  build-and-push-image:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Build and Push with Gradle
      id: build-and-push-to-ecr
      run: ./gradlew jib -x test --image $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
